/**
 * Prisma Database Seed Script
 *
 * Seeds the database with:
 * - 6 Basic Runes
 * - 12 Real Riftbound cards
 * - Test users
 */

import { PrismaClient, CardType, Rarity } from '../src/generated/prisma';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // ============================================================================
  // Seed Card Definitions
  // ============================================================================

  console.log('\n📦 Seeding card definitions...');

  const cards = [
    // ==========================================================================
    // TEST CARDS (for API testing - no scripts)
    // ==========================================================================

    // Test Legend
    {
      id: 'test-legend-1',
      name: 'Test Legend',
      cardType: CardType.LEGEND,
      rarity: Rarity.MYTHIC,
      energyCost: 0,
      powerCosts: [],
      description: 'A test champion legend with no abilities.',
      flavorText: 'For testing purposes only.',
      might: null,
      subtypes: ['test'],
      domains: ['fury'],
      keywords: [],
      tags: ['test', 'champion_legend'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-L-1',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },

    // Test Champion
    {
      id: 'test-champion-1',
      name: 'Test Champion',
      cardType: CardType.CHAMPION,
      rarity: Rarity.RARE,
      energyCost: 3,
      powerCosts: [],
      description: 'A test champion unit.',
      flavorText: 'For testing purposes only.',
      might: 4,
      subtypes: ['test'],
      domains: ['fury'],
      keywords: [],
      tags: ['test', 'champion'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-C-1',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },

    // Test Units (10 vanilla units)
    {
      id: 'test-unit-0',
      name: 'Test Unit 0',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 2,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 2,
      subtypes: [],
      domains: ['fury'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-0',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-1',
      name: 'Test Unit 1',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 2,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 2,
      subtypes: [],
      domains: ['fury'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-1',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-2',
      name: 'Test Unit 2',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 3,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 3,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-2',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-3',
      name: 'Test Unit 3',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 3,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 3,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-3',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-4',
      name: 'Test Unit 4',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 4,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 4,
      subtypes: [],
      domains: ['mind'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-4',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-5',
      name: 'Test Unit 5',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 4,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 4,
      subtypes: [],
      domains: ['mind'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-5',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-6',
      name: 'Test Unit 6',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 5,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 5,
      subtypes: [],
      domains: ['body'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-6',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-7',
      name: 'Test Unit 7',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 5,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 5,
      subtypes: [],
      domains: ['body'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-7',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-8',
      name: 'Test Unit 8',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 6,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 6,
      subtypes: [],
      domains: ['chaos'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-8',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-unit-9',
      name: 'Test Unit 9',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 6,
      powerCosts: [],
      description: 'A basic test unit.',
      flavorText: null,
      might: 6,
      subtypes: [],
      domains: ['order'],
      keywords: [],
      tags: ['test'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-U-9',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },

    // Test Runes (6 basic runes)
    {
      id: 'test-rune-0',
      name: 'Test Fury Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['fury'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-0',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'test-rune-1',
      name: 'Test Calm Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-1',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'test-rune-2',
      name: 'Test Mind Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['mind'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-2',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'test-rune-3',
      name: 'Test Body Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['body'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-3',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'test-rune-4',
      name: 'Test Chaos Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['chaos'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-4',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'test-rune-5',
      name: 'Test Order Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'Basic rune that provides energy.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['order'],
      keywords: [],
      tags: ['test', 'rune'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-R-5',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: true,
    },

    // Test Battlefields (3 battlefields)
    {
      id: 'test-battlefield-1',
      name: 'Test Battlefield 1',
      cardType: CardType.BATTLEFIELD,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'A test battlefield with no special effects.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['fury'],
      keywords: [],
      tags: ['test', 'battlefield'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-BF-1',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-battlefield-2',
      name: 'Test Battlefield 2',
      cardType: CardType.BATTLEFIELD,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'A test battlefield with no special effects.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['test', 'battlefield'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-BF-2',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'test-battlefield-3',
      name: 'Test Battlefield 3',
      cardType: CardType.BATTLEFIELD,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: 'A test battlefield with no special effects.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['mind'],
      keywords: [],
      tags: ['test', 'battlefield'],
      scriptPath: null,
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'TEST-BF-3',
      setCode: 'TEST',
      setName: 'Test Set',
      isSignature: false,
      isBasicRune: false,
    },

    // ==========================================================================
    // BASIC RUNES (6 cards)
    // ==========================================================================
    {
      id: 'BASIC_RUNE_FURY',
      name: 'Fury Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Fury] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['fury'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-FURY',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'BASIC_RUNE_CALM',
      name: 'Calm Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Calm] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-CALM',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'BASIC_RUNE_MIND',
      name: 'Mind Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Mind] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['mind'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-MIND',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'BASIC_RUNE_BODY',
      name: 'Body Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Body] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['body'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-BODY',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'BASIC_RUNE_CHAOS',
      name: 'Chaos Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Chaos] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['chaos'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-CHAOS',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },
    {
      id: 'BASIC_RUNE_ORDER',
      name: 'Order Rune',
      cardType: CardType.RUNE,
      rarity: Rarity.COMMON,
      energyCost: 0,
      powerCosts: [],
      description: '[T]: Add [1] energy. Recycle this: Add [Order] power.',
      flavorText: null,
      might: null,
      subtypes: [],
      domains: ['order'],
      keywords: [],
      tags: ['rune', 'basic'],
      scriptPath: 'basic-rune.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'R-ORDER',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: true,
    },

    // ==========================================================================
    // REAL RIFTBOUND CARDS (12 cards)
    // ==========================================================================

    // LEGENDS (2)
    {
      id: 'DARIUS_HAND_OF_NOXUS',
      name: 'Darius, Hand of Noxus',
      cardType: CardType.LEGEND,
      rarity: Rarity.RARE,
      energyCost: 0,
      powerCosts: [],
      description: 'tap REACTION, LEGION - ADD 1 (Abilities that add resources can\'t be reacted to. Get the effect if you\'ve played a card this turn.)',
      flavorText: 'Victory through strength.',
      might: null,
      subtypes: ['darius'],
      domains: ['fury', 'order'],
      keywords: ['reaction', 'legion'],
      tags: ['darius', 'champion_legend'],
      scriptPath: 'darius-hand-of-noxus.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'L-DARIUS',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'YASUO_UNFORGIVEN',
      name: 'Yasuo, Unforgiven',
      cardType: CardType.LEGEND,
      rarity: Rarity.RARE,
      energyCost: 0,
      powerCosts: [],
      description: '2, tap: Move a friendly unit to or from its base.',
      flavorText: 'Death is like the wind - always by my side.',
      might: null,
      subtypes: ['yasuo'],
      domains: ['calm', 'chaos'],
      keywords: [],
      tags: ['yasuo', 'champion_legend'],
      scriptPath: 'yasuo-unforgiven.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'L-YASUO',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },

    // UNITS (5)
    {
      id: 'BRAZEN_BUCCANEER',
      name: 'Brazen Buccaneer',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 6,
      powerCosts: [],
      description: 'As you play me, you may discard a card as an additional cost. If you do, reduce my cost by 2.',
      flavorText: 'For the right price, even the seas bow.',
      might: 5,
      subtypes: ['pirate'],
      domains: ['fury'],
      keywords: [],
      tags: ['pirate', 'bilgewater'],
      scriptPath: 'brazen-buccaneer.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'U-BUCCANEER',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'DARIUS_TRIFARIAN',
      name: 'Darius, Trifarian',
      cardType: CardType.UNIT,
      rarity: Rarity.RARE,
      energyCost: 5,
      powerCosts: [{ domain: 'fury', amount: 1 }],
      description: 'When you play your second card in a turn, give me +2 might this turn and ready me.',
      flavorText: 'Only the strong survive.',
      might: 5,
      subtypes: ['darius', 'trifarian'],
      domains: ['fury'],
      keywords: [],
      tags: ['darius', 'noxus'],
      scriptPath: 'darius-trifarian.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'U-DARIUS',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'VI_DESTRUCTIVE',
      name: 'Vi, Destructive',
      cardType: CardType.UNIT,
      rarity: Rarity.RARE,
      energyCost: 2,
      powerCosts: [{ domain: 'fury', amount: 1 }],
      description: 'GANKING (I can move from battlefield to battlefield.)\nRecycle 1 from your trash: Give me +1 might this turn.',
      flavorText: 'Punch first. Ask questions while punching.',
      might: 3,
      subtypes: ['vi'],
      domains: ['fury'],
      keywords: ['ganking'],
      tags: ['vi', 'piltover'],
      scriptPath: 'vi-destructive.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'U-VI',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'YASUO_REMORSEFUL',
      name: 'Yasuo, Remorseful',
      cardType: CardType.UNIT,
      rarity: Rarity.RARE,
      energyCost: 6,
      powerCosts: [{ domain: 'calm', amount: 2 }],
      description: 'When I attack, deal damage equal to my Might to an enemy unit here.',
      flavorText: 'The road to ruin is shorter than you think.',
      might: 6,
      subtypes: ['yasuo'],
      domains: ['calm'],
      keywords: [],
      tags: ['yasuo', 'ionia'],
      scriptPath: 'yasuo-remorseful.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: 'Riot Games',
      cardNumber: 'U-YASUO',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'PLAYFUL_PHANTOM',
      name: 'Playful Phantom',
      cardType: CardType.UNIT,
      rarity: Rarity.COMMON,
      energyCost: 5,
      powerCosts: [],
      description: 'Vanilla unit - no special abilities.',
      flavorText: 'Ethereal and playful, yet mighty.',
      might: 5,
      subtypes: ['spirit'],
      domains: ['calm'],
      keywords: [],
      tags: ['spirit', 'shadow_isles'],
      scriptPath: 'playful-phantom.card.ts',
      hasScript: false,
      imageUrl: null,
      artist: null,
      cardNumber: 'U-PHANTOM',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },

    // SPELLS (3)
    {
      id: 'DISINTEGRATE',
      name: 'Disintegrate',
      cardType: CardType.SPELL,
      rarity: Rarity.COMMON,
      energyCost: 4,
      powerCosts: [],
      description: 'ACTION (Play on your turn or in showdowns.)\nDeal 3 to a unit at a battlefield. If this kills it, do this: draw 1.',
      flavorText: 'Reduced to ash.',
      might: null,
      subtypes: [],
      domains: ['fury'],
      keywords: ['action'],
      tags: ['damage', 'spell'],
      scriptPath: 'disintegrate.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'S-DISINTEGRATE',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'CHARM',
      name: 'Charm',
      cardType: CardType.SPELL,
      rarity: Rarity.COMMON,
      energyCost: 1,
      powerCosts: [{ domain: 'calm', amount: 1 }],
      description: 'Move an enemy unit.',
      flavorText: 'A gentle push.',
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: [],
      tags: ['movement', 'spell'],
      scriptPath: 'charm.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'S-CHARM',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'DEFY',
      name: 'Defy',
      cardType: CardType.SPELL,
      rarity: Rarity.COMMON,
      energyCost: 1,
      powerCosts: [{ domain: 'calm', amount: 1 }],
      description: 'REACTION (Play any time, even before spells and abilities resolve.)\nCounter a spell that costs no more than 4 and no more than rune.',
      flavorText: 'Not today.',
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: ['reaction'],
      tags: ['counter', 'spell'],
      scriptPath: 'defy.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'S-DEFY',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },

    // GEAR (2)
    {
      id: 'SEAL_OF_RAGE',
      name: 'Seal of Rage',
      cardType: CardType.GEAR,
      rarity: Rarity.RARE,
      energyCost: 0,
      powerCosts: [{ domain: 'fury', amount: 1 }],
      description: 'tap: REACTION - ADD fury. (Abilities that add resources can\'t be reacted to.)',
      flavorText: 'Fury unleashed.',
      might: null,
      subtypes: [],
      domains: ['fury'],
      keywords: ['reaction'],
      tags: ['gear', 'resource'],
      scriptPath: 'seal-of-rage.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'G-SEAL',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
    {
      id: 'ZHONYAS_HOURGLASS',
      name: "Zhonya's Hourglass",
      cardType: CardType.GEAR,
      rarity: Rarity.RARE,
      energyCost: 2,
      powerCosts: [],
      description: 'HIDDEN (Hide now for [A] to react with later for 0.)\nIf a friendly unit would die, kill this instead. Heal that unit, exhaust it, and recall it. (Send it to base. This isn\'t a move.)',
      flavorText: 'Time stands still.',
      might: null,
      subtypes: [],
      domains: ['calm'],
      keywords: ['hidden'],
      tags: ['gear', 'protection'],
      scriptPath: 'zhonyas-hourglass.card.ts',
      hasScript: true,
      imageUrl: null,
      artist: null,
      cardNumber: 'G-ZHONYA',
      setCode: 'BASE',
      setName: 'Base Set',
      isSignature: false,
      isBasicRune: false,
    },
  ];

  for (const card of cards) {
    await prisma.cardDefinition.upsert({
      where: { id: card.id },
      update: card,
      create: card,
    });
    console.log(`  ✓ ${card.name} (${card.cardType})`);
  }

  console.log(`\n✅ Seeded ${cards.length} cards (21 test cards + 6 basic runes + 12 real Riftbound cards)`);

  // ============================================================================
  // Seed Test Users
  // ============================================================================

  console.log('\n👤 Seeding test users...');

  const testUsers = [
    {
      id: 'test-user-1',
      email: 'player1@test.com',
      username: 'player1',
      passwordHash: '$2a$10$test.hash.placeholder',
      displayName: 'Test Player 1',
      avatarUrl: null,
    },
    {
      id: 'test-user-2',
      email: 'player2@test.com',
      username: 'player2',
      passwordHash: '$2a$10$test.hash.placeholder',
      displayName: 'Test Player 2',
      avatarUrl: null,
    },
  ];

  for (const user of testUsers) {
    await prisma.user.upsert({
      where: { id: user.id },
      update: user,
      create: user,
    });
    console.log(`  ✓ ${user.username}`);
  }

  console.log(`\n✅ Seeded ${testUsers.length} users`);
  console.log('\n🎉 Seed completed successfully!');
  console.log('\n📁 Card scripts should be placed in: src/cards/');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
